import crypto from 'node:crypto'
import type { SetupConfig } from '../types.js'

function generateSecret(): string {
  return crypto.randomBytes(32).toString('base64')
}

export function generateEnvFile(config: SetupConfig): string {
  const protocol = config.useHttps ? 'https' : 'http'
  const portSuffix = (config.useHttps && config.httpPort === 443) || (!config.useHttps && config.httpPort === 80)
    ? ''
    : `:${config.httpPort}`
  const baseUrl = `${protocol}://${config.domain}${portSuffix}`
  const domainWithPort = `${config.domain}${portSuffix}`

  const topDomain = config.domain === 'localhost'
    ? 'localhost'
    : config.domain.split('.').slice(-2).join('.')

  const cookieDomain = config.domain === 'localhost'
    ? '.localhost'
    : `.${topDomain}`

  const nextAuthSecret = generateSecret()
  const jwtSecret = generateSecret()
  const collabInternalKey = generateSecret()

  const lines: string[] = [
    '# Launch LMS Environment Variables',
    '# Generated by Launch LMS CLI',
    '',
    '# =============================================================================',
    '# Domain & Hosting Configuration',
    '# =============================================================================',
    '',
    `LAUNCHLMS_DOMAIN=${domainWithPort}`,
    `HTTP_PORT=${config.httpPort}`,
    '',
    '# =============================================================================',
    '# Frontend Environment Variables (NEXT_PUBLIC_*)',
    '# =============================================================================',
    '',
    `NEXT_PUBLIC_LAUNCHLMS_API_URL=${baseUrl}/api/v1/`,
    `NEXT_PUBLIC_LAUNCHLMS_BACKEND_URL=${baseUrl}/`,
    `NEXT_PUBLIC_LAUNCHLMS_DOMAIN=${domainWithPort}`,
    `NEXT_PUBLIC_LAUNCHLMS_TOP_DOMAIN=${topDomain}`,
    'NEXT_PUBLIC_LAUNCHLMS_MULTI_ORG=False',
    'NEXT_PUBLIC_LAUNCHLMS_DEFAULT_ORG=default',
    `NEXT_PUBLIC_LAUNCHLMS_HTTPS=${config.useHttps ? 'True' : 'False'}`,
  ]

  if (config.unsplashEnabled && config.unsplashAccessKey) {
    lines.push(`NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=${config.unsplashAccessKey}`)
  }

  lines.push(
    '',
    '# =============================================================================',
    '# NextAuth Configuration',
    '# =============================================================================',
    '',
    `NEXTAUTH_URL=${baseUrl}`,
    `NEXTAUTH_SECRET=${nextAuthSecret}`,
  )

  if (config.googleOAuthEnabled && config.googleClientId && config.googleClientSecret) {
    lines.push(
      `LAUNCHLMS_GOOGLE_CLIENT_ID=${config.googleClientId}`,
      `LAUNCHLMS_GOOGLE_CLIENT_SECRET=${config.googleClientSecret}`,
    )
  }

  lines.push(
    '',
    '# =============================================================================',
    '# Backend Configuration',
    '# =============================================================================',
    '',
    `LAUNCHLMS_SQL_CONNECTION_STRING=${config.useExternalDb
      ? config.externalDbConnectionString
      : `postgresql://launch-lms:${config.dbPassword}@db:5432/launch-lms`}`,
    `LAUNCHLMS_REDIS_CONNECTION_STRING=${config.useExternalRedis
      ? config.externalRedisConnectionString
      : 'redis://redis:6379/launch-lms'}`,
    `LAUNCHLMS_COOKIE_DOMAIN=${cookieDomain}`,
    'LAUNCHLMS_PORT=9000',
    '',
    '# =============================================================================',
    '# Security',
    '# =============================================================================',
    '',
    `LAUNCHLMS_AUTH_JWT_SECRET_KEY=${jwtSecret}`,
    `LAUNCHLMS_INITIAL_ADMIN_EMAIL=${config.adminEmail}`,
    `LAUNCHLMS_INITIAL_ADMIN_PASSWORD=${config.adminPassword}`,
    '',
    '# =============================================================================',
    '# Collaboration Server',
    '# =============================================================================',
    '',
    `COLLAB_INTERNAL_KEY=${collabInternalKey}`,
    `LAUNCHLMS_REDIS_URL=${config.useExternalRedis
      ? config.externalRedisConnectionString
      : 'redis://redis:6379'}`,
    `NEXT_PUBLIC_COLLAB_URL=${config.useHttps ? 'wss' : 'ws'}://${config.domain}${portSuffix}/collab`,
    '',
    '# =============================================================================',
    '# General Settings',
    '# =============================================================================',
    '',
    'LAUNCHLMS_DEVELOPMENT_MODE=False',
    'LAUNCHLMS_LOGFIRE_ENABLED=False',
  )

  if (config.aiEnabled && config.geminiApiKey) {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      `LAUNCHLMS_GEMINI_API_KEY=${config.geminiApiKey}`,
      'LAUNCHLMS_IS_AI_ENABLED=True',
    )
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# AI Configuration',
      '# =============================================================================',
      '',
      'LAUNCHLMS_IS_AI_ENABLED=False',
    )
  }

  if (config.emailEnabled) {
    const provider = config.emailProvider || 'resend'
    lines.push(
      '',
      '# =============================================================================',
      '# Email Configuration',
      '# =============================================================================',
      '',
      `LAUNCHLMS_EMAIL_PROVIDER=${provider}`,
      `LAUNCHLMS_SYSTEM_EMAIL_ADDRESS=${config.systemEmailAddress || `noreply@${config.domain}`}`,
    )

    if (provider === 'resend' && config.resendApiKey) {
      lines.push(`LAUNCHLMS_RESEND_API_KEY=${config.resendApiKey}`)
    }

    if (provider === 'smtp') {
      if (config.smtpHost) lines.push(`LAUNCHLMS_SMTP_HOST=${config.smtpHost}`)
      lines.push(`LAUNCHLMS_SMTP_PORT=${config.smtpPort || 587}`)
      if (config.smtpUsername) lines.push(`LAUNCHLMS_SMTP_USERNAME=${config.smtpUsername}`)
      if (config.smtpPassword) lines.push(`LAUNCHLMS_SMTP_PASSWORD=${config.smtpPassword}`)
      lines.push(`LAUNCHLMS_SMTP_USE_TLS=${config.smtpUseTls !== false ? 'True' : 'False'}`)
    }
  }

  if (config.s3Enabled && config.s3BucketName) {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'LAUNCHLMS_CONTENT_DELIVERY_TYPE=s3api',
      `LAUNCHLMS_S3_API_BUCKET_NAME=${config.s3BucketName}`,
    )
    if (config.s3EndpointUrl) {
      lines.push(`LAUNCHLMS_S3_API_ENDPOINT_URL=${config.s3EndpointUrl}`)
    }
  } else {
    lines.push(
      '',
      '# =============================================================================',
      '# Content Delivery',
      '# =============================================================================',
      '',
      'LAUNCHLMS_CONTENT_DELIVERY_TYPE=filesystem',
    )
  }

  if (!config.useExternalDb) {
    lines.push(
      '',
      '# =============================================================================',
      '# Database Configuration',
      '# =============================================================================',
      '',
      'POSTGRES_USER=launch-lms',
      `POSTGRES_PASSWORD=${config.dbPassword}`,
      'POSTGRES_DB=launch-lms',
      '',
    )
  } else {
    lines.push('')
  }

  return lines.join('\n')
}
