'use client'

import React from 'react'
import useSWR, { mutate } from 'swr'
import toast from 'react-hot-toast'
import { CheckCircle2, ChevronDown, ChevronRight, ClipboardCheck, FileText, Loader2, Plus, Send, Trash2, Users } from 'lucide-react'
import Modal from '@components/Objects/StyledElements/Modal/Modal'
import { getAPIUrl } from '@services/config/config'
import { requirementsApi } from '@services/programs/programs'
import { swrFetcher } from '@services/utils/ts/requests'
import { cn } from '@/lib/utils'

const frameworksKey = (orgId: number) => `${getAPIUrl()}planning/requirements?org_id=${orgId}`

export function RequirementsAdmin({ orgId, token }: { orgId: number; token?: string }) {
  const key = orgId && token ? frameworksKey(orgId) : null
  const { data: frameworks = [], isLoading } = useSWR(key, (url) => swrFetcher(url, token), { revalidateOnFocus: false })
  const [selectedUuid, setSelectedUuid] = React.useState('')
  const selected = frameworks.find((item: any) => item.framework_uuid === selectedUuid) || frameworks[0]
  React.useEffect(() => { if (!selectedUuid && frameworks[0]) setSelectedUuid(frameworks[0].framework_uuid) }, [frameworks, selectedUuid])
  const refresh = () => mutate(key as string)
  if (isLoading) return <Loading />
  return <div className="px-10 pb-10 pt-6"><div className="grid gap-6 xl:grid-cols-[300px_minmax(0,1fr)]">
    <aside className="rounded-xl border border-border bg-card p-4 shadow-xs"><div className="flex items-center justify-between"><div><h2 className="font-bold">Frameworks</h2><p className="mt-1 text-xs text-muted-foreground">Organization compliance checklists</p></div><CreateFramework orgId={orgId} token={token} refresh={refresh} /></div>
      <div className="mt-4 space-y-2">{frameworks.map((item: any) => <button key={item.framework_uuid} onClick={() => setSelectedUuid(item.framework_uuid)} className={cn('w-full rounded-lg border p-3 text-left', selected?.framework_uuid === item.framework_uuid ? 'border-blue-500 bg-blue-50' : 'border-border hover:bg-muted')}><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-bold">{item.name}</span><span className={cn('rounded-full px-2 py-0.5 text-[9px] font-black uppercase', item.status === 'published' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700')}>{item.status}</span></div><p className="mt-1 text-[11px] text-muted-foreground">v{item.version} · {item.nodes.length} nodes · {item.enrollment_count} learners</p></button>)}{!frameworks.length && <p className="rounded-lg border border-dashed border-border px-3 py-10 text-center text-xs text-muted-foreground">Create the first requirement framework.</p>}</div>
    </aside>
    {selected ? <FrameworkEditor key={`${selected.framework_uuid}:${selected.version}`} framework={selected} orgId={orgId} token={token} refresh={refresh} /> : <div className="rounded-xl border border-dashed border-border bg-card py-24 text-center"><ClipboardCheck className="mx-auto text-gray-300" size={40} /><p className="mt-3 text-sm font-bold">No framework selected</p></div>}
  </div></div>
}

function CreateFramework({ orgId, token, refresh }: any) {
  const [open, setOpen] = React.useState(false), [name, setName] = React.useState(''), [description, setDescription] = React.useState(''), [saving, setSaving] = React.useState(false)
  const create = async () => { if (!name.trim()) return; setSaving(true); try { await requirementsApi.create(orgId, { name, description, nodes: [] }, token); await refresh(); setOpen(false); setName(''); setDescription(''); toast.success('Requirement framework created.') } catch (error: any) { toast.error(error?.message || 'Could not create the framework.') } finally { setSaving(false) } }
  return <Modal isDialogOpen={open} onOpenChange={setOpen} minHeight="no-min" minWidth="md" dialogTitle="New requirement framework" dialogDescription="Create an organization-owned compliance checklist." dialogTrigger={<button className="rounded-lg bg-black p-2 text-white" aria-label="New framework"><Plus size={15} /></button>} dialogContent={<div className="space-y-4 p-2"><Field label="Name"><input autoFocus value={name} onChange={(event) => setName(event.target.value)} className="h-10 w-full rounded-lg border border-border px-3 text-sm" placeholder="Career readiness requirements" /></Field><Field label="Description"><textarea value={description} onChange={(event) => setDescription(event.target.value)} className="min-h-24 w-full rounded-lg border border-border p-3 text-sm" /></Field><button onClick={() => void create()} disabled={!name.trim() || saving} className="ml-auto flex items-center gap-2 rounded-lg bg-black px-5 py-2 text-xs font-bold text-white disabled:opacity-40">{saving && <Loader2 className="animate-spin" size={14} />}Create</button></div>} />
}

function FrameworkEditor({ framework, orgId, token, refresh }: any) {
  const [name, setName] = React.useState(framework.name), [description, setDescription] = React.useState(framework.description || ''), [nodes, setNodes] = React.useState<any[]>(framework.nodes || []), [saving, setSaving] = React.useState(false), [publishing, setPublishing] = React.useState(false)
  const addNode = () => setNodes((current) => [...current, { node_uuid: `requirement_node_${crypto.randomUUID()}`, parent_node_uuid: null, code: '', title: '', description: '', position: current.length, metadata: {} }])
  const patchNode = (uuid: string, patch: any) => setNodes((current) => current.map((node) => node.node_uuid === uuid ? { ...node, ...patch } : node))
  const removeNode = (uuid: string) => setNodes((current) => current.filter((node) => node.node_uuid !== uuid).map((node) => node.parent_node_uuid === uuid ? { ...node, parent_node_uuid: null } : node))
  const save = async () => { if (!name.trim() || nodes.some((node) => !node.title.trim())) return; setSaving(true); try { await requirementsApi.update(orgId, framework.framework_uuid, { name, description, nodes: nodes.map((node, position) => ({ ...node, position })) }, token); await refresh(); toast.success(framework.status === 'published' ? 'Draft version created.' : 'Framework saved.') } catch (error: any) { toast.error(error?.message || 'Could not save the framework.') } finally { setSaving(false) } }
  const publish = async () => { if (framework.status === 'published') return; setPublishing(true); try { const result = await requirementsApi.publish(orgId, framework.framework_uuid, token); await refresh(); toast.success(`Version ${result.version} published.`); if (result.active_incomplete_enrollments > 0 && window.confirm(`Update ${result.active_incomplete_enrollments} active incomplete learner${result.active_incomplete_enrollments === 1 ? '' : 's'} to this version? Completed enrollments will remain unchanged.`)) { const migration = await requirementsApi.migrateActive(orgId, framework.framework_uuid, null, token); toast.success(`${migration.updated} active learner${migration.updated === 1 ? '' : 's'} updated.`); await refresh() } } catch (error: any) { toast.error(error?.message || 'Could not publish the framework.') } finally { setPublishing(false) } }
  return <main className="space-y-5"><section className="rounded-xl border border-border bg-card p-6 shadow-xs"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-wider text-blue-600">Version {framework.version} · {framework.status}</p><h2 className="mt-1 text-xl font-black">Framework definition</h2><p className="mt-1 text-sm text-muted-foreground">Published versions remain available to existing learner snapshots.</p></div><div className="flex gap-2"><button onClick={() => void save()} disabled={saving || !name.trim() || nodes.some((node) => !node.title.trim())} className="rounded-lg border border-border px-4 py-2 text-xs font-bold disabled:opacity-40">{saving ? 'Saving…' : 'Save draft'}</button><button onClick={() => void publish()} disabled={publishing || !nodes.length} className="flex items-center gap-2 rounded-lg bg-black px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{publishing ? <Loader2 className="animate-spin" size={14} /> : <CheckCircle2 size={14} />}Publish</button></div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Name"><input value={name} onChange={(event) => setName(event.target.value)} className="h-10 w-full rounded-lg border border-border px-3 text-sm" /></Field><Field label="Description"><input value={description} onChange={(event) => setDescription(event.target.value)} className="h-10 w-full rounded-lg border border-border px-3 text-sm" /></Field></div>
    <div className="mt-6"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold">Requirement nodes</h3><p className="mt-1 text-xs text-muted-foreground">Nodes without children count toward learner completion.</p></div><button onClick={addNode} className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-bold"><Plus size={13} />Node</button></div><div className="mt-3 space-y-2">{nodes.map((node) => <div key={node.node_uuid} className="grid gap-2 rounded-lg border border-border p-3 md:grid-cols-[100px_minmax(180px,1fr)_minmax(150px,0.7fr)_32px]"><input value={node.code} onChange={(event) => patchNode(node.node_uuid, { code: event.target.value })} placeholder="Code" className="h-9 rounded-md border border-border px-2 text-xs" /><input value={node.title} onChange={(event) => patchNode(node.node_uuid, { title: event.target.value })} placeholder="Requirement title" className="h-9 rounded-md border border-border px-2 text-sm font-semibold" /><select value={node.parent_node_uuid || ''} onChange={(event) => patchNode(node.node_uuid, { parent_node_uuid: event.target.value || null })} className="h-9 rounded-md border border-border bg-card px-2 text-xs"><option value="">Top level</option>{nodes.filter((candidate) => candidate.node_uuid !== node.node_uuid).map((candidate) => <option key={candidate.node_uuid} value={candidate.node_uuid}>Under {candidate.code ? `${candidate.code} · ` : ''}{candidate.title || 'Untitled'}</option>)}</select><button onClick={() => removeNode(node.node_uuid)} className="text-red-600"><Trash2 size={15} /></button></div>)}{!nodes.length && <button onClick={addNode} className="w-full rounded-lg border border-dashed border-border py-10 text-xs font-semibold text-muted-foreground">Add the first requirement node</button>}</div></div>
  </section>{framework.published_version ? <AssignmentPanel framework={framework} orgId={orgId} token={token} refresh={refresh} /> : null}</main>
}

function AssignmentPanel({ framework, orgId, token, refresh }: any) {
  const peopleKey = `${getAPIUrl()}orgs/${orgId}/users?page=1&limit=100`
  const groupsKey = `${getAPIUrl()}usergroups/org/${orgId}?org_id=${orgId}`
  const { data: people } = useSWR(token ? peopleKey : null, (url) => swrFetcher(url, token))
  const { data: groups } = useSWR(token ? groupsKey : null, (url) => swrFetcher(url, token))
  const [target, setTarget] = React.useState(''), [saving, setSaving] = React.useState(false)
  const assign = async () => { const [type, id] = target.split(':'); if (!id) return; setSaving(true); try { const result = await requirementsApi.assign(orgId, framework.framework_uuid, type === 'group' ? { usergroup_id: Number(id) } : { user_id: Number(id) }, token); toast.success(`Assigned to ${result.enrollment_count} learner${result.enrollment_count === 1 ? '' : 's'}.`); setTarget(''); await refresh() } catch (error: any) { toast.error(error?.message || 'Could not assign the framework.') } finally { setSaving(false) } }
  const memberships = people?.items || []
  return <section className="rounded-xl border border-border bg-card p-6 shadow-xs"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="flex items-center gap-2 text-lg font-bold"><Users size={18} />Direct assignments</h2><p className="mt-1 text-sm text-muted-foreground">Requirements apply only after this framework is assigned to a learner or group.</p></div><div className="flex min-w-[360px] gap-2"><select value={target} onChange={(event) => setTarget(event.target.value)} className="h-10 min-w-0 flex-1 rounded-lg border border-border bg-card px-3 text-sm"><option value="">Choose a learner or group</option><optgroup label="Learners">{memberships.map((membership: any) => { const user = membership.user || membership; return <option key={`user:${user.id}`} value={`user:${user.id}`}>{[user.first_name, user.last_name].filter(Boolean).join(' ') || user.username}</option> })}</optgroup><optgroup label="Groups">{(groups || []).map((group: any) => <option key={`group:${group.id}`} value={`group:${group.id}`}>{group.name}</option>)}</optgroup></select><button onClick={() => void assign()} disabled={!target || saving} className="flex items-center gap-2 rounded-lg bg-black px-4 text-xs font-bold text-white disabled:opacity-40">{saving ? <Loader2 className="animate-spin" size={14} /> : <Send size={14} />}Assign</button></div></div></section>
}

export function RequirementsReporting({ orgId, token }: { orgId: number; token?: string }) {
  const { data: frameworks = [], isLoading: frameworksLoading } = useSWR(orgId && token ? frameworksKey(orgId) : null, (url) => swrFetcher(url, token))
  const { data: groups = [] } = useSWR(orgId && token ? `${getAPIUrl()}usergroups/org/${orgId}?org_id=${orgId}` : null, (url) => swrFetcher(url, token))
  const [frameworkUuid, setFrameworkUuid] = React.useState(''), [version, setVersion] = React.useState(''), [groupId, setGroupId] = React.useState(''), [nodeUuid, setNodeUuid] = React.useState(''), [status, setStatus] = React.useState(''), [expanded, setExpanded] = React.useState('')
  React.useEffect(() => { if (!frameworkUuid && frameworks[0]?.framework_uuid) setFrameworkUuid(frameworks[0].framework_uuid) }, [frameworkUuid, frameworks])
  const selected = frameworks.find((item: any) => item.framework_uuid === frameworkUuid)
  React.useEffect(() => { if (selected && (!version || !selected.versions.some((item: any) => String(item.version) === version))) setVersion(String(selected.published_version || selected.version)) }, [selected, version])
  const { data: selectedVersion } = useSWR(frameworkUuid && version && token ? ['requirement-version', frameworkUuid, version, token] : null, () => requirementsApi.get(orgId, frameworkUuid, token, Number(version)))
  const reportKey = frameworkUuid && version && token ? ['requirement-report', orgId, frameworkUuid, version, groupId, nodeUuid, status, token] : null
  const { data: report, isLoading } = useSWR(reportKey, () => requirementsApi.report(orgId, { framework_uuid: frameworkUuid, version: Number(version), usergroup_id: groupId ? Number(groupId) : undefined, node_uuid: nodeUuid || undefined, status: status || undefined }, token), { revalidateOnFocus: false })
  const leaves = selectedVersion ? leafNodes(selectedVersion.nodes || []) : []
  if (frameworksLoading) return <Loading />
  return <div className="px-10 pb-10 pt-6"><section className="rounded-xl border border-border bg-card p-6 shadow-xs"><div><h2 className="text-lg font-bold">Requirement attainment</h2><p className="mt-1 text-sm text-muted-foreground">Report against each learner’s directly assigned framework snapshot.</p></div><div className="mt-5 grid gap-3 md:grid-cols-5"><select value={frameworkUuid} onChange={(event) => { setFrameworkUuid(event.target.value); setVersion(''); setNodeUuid('') }} className="h-10 rounded-lg border border-border bg-card px-3 text-sm"><option value="">Choose framework</option>{frameworks.filter((item: any) => item.published_version).map((item: any) => <option key={item.framework_uuid} value={item.framework_uuid}>{item.name}</option>)}</select><select value={version} onChange={(event) => { setVersion(event.target.value); setNodeUuid('') }} className="h-10 rounded-lg border border-border bg-card px-3 text-sm"><option value="">Version</option>{(selected?.versions || []).filter((item: any) => item.status === 'published').map((item: any) => <option key={item.version} value={item.version}>Version {item.version}</option>)}</select><select value={groupId} onChange={(event) => setGroupId(event.target.value)} className="h-10 rounded-lg border border-border bg-card px-3 text-sm"><option value="">All learners</option>{groups.map((group: any) => <option key={group.id} value={group.id}>{group.name}</option>)}</select><select value={nodeUuid} onChange={(event) => setNodeUuid(event.target.value)} className="h-10 rounded-lg border border-border bg-card px-3 text-sm"><option value="">All requirements</option>{leaves.map((node: any) => <option key={node.node_uuid} value={node.node_uuid}>{node.code ? `${node.code} · ` : ''}{node.title}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-10 rounded-lg border border-border bg-card px-3 text-sm"><option value="">Any status</option><option value="satisfied">Satisfied</option><option value="not_satisfied">Not satisfied</option></select></div>
    {report ? <div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat label="Learners" value={report.learner_count} /><Stat label="Framework complete" value={report.completed_count} /><Stat label="Completion rate" value={`${report.learner_count ? Math.round(report.completed_count / report.learner_count * 100) : 0}%`} /></div> : null}
    <div className="mt-5 overflow-x-auto rounded-xl border border-border">{isLoading ? <Loading /> : report?.rows?.length ? <table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted/60 text-[10px] font-black uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-3">Learner</th><th className="px-4 py-3">Version</th>{leaves.map((node: any) => <th key={node.node_uuid} className="max-w-32 px-3 py-3" title={node.title}>{node.code || node.title}</th>)}<th className="px-4 py-3">Attainment</th><th className="px-4 py-3">Status</th><th className="w-10" /></tr></thead><tbody className="divide-y divide-border">{report.rows.map((row: any) => <React.Fragment key={row.enrollment_uuid}><tr className="hover:bg-muted/30"><td className="px-4 py-3 font-bold">{[row.user.first_name, row.user.last_name].filter(Boolean).join(' ') || row.user.username}</td><td className="px-4 py-3 text-muted-foreground">v{row.framework.version}</td>{leaves.map((node: any) => <td key={node.node_uuid} className="px-3 py-3 text-center">{row.attained_node_uuids.includes(node.node_uuid) ? <CheckCircle2 size={16} className="mx-auto text-green-600" /> : <span className="text-gray-300">—</span>}</td>)}<td className="px-4 py-3"><span className="font-bold">{row.completed}/{row.total}</span><div className="mt-1 h-1.5 w-28 overflow-hidden rounded-full bg-muted"><div className="h-full bg-blue-600" style={{ width: `${row.total ? row.completed / row.total * 100 : 0}%` }} /></div></td><td className="px-4 py-3"><span className={cn('rounded-full px-2 py-1 text-[10px] font-black uppercase', row.status === 'completed' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700')}>{row.status}</span></td><td><button onClick={() => setExpanded(expanded === row.enrollment_uuid ? '' : row.enrollment_uuid)}>{expanded === row.enrollment_uuid ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</button></td></tr>{expanded === row.enrollment_uuid ? <tr><td colSpan={5 + leaves.length} className="bg-muted/30 px-5 py-4"><div className="grid gap-3 md:grid-cols-2">{row.sources.length ? row.sources.map((source: any) => <div key={source.source_uuid} className="rounded-lg border border-border bg-card p-3"><p className="flex items-center gap-2 text-xs font-bold"><FileText size={13} />{source.objective_title}</p><p className="mt-1 text-[11px] text-muted-foreground">{source.verified_at ? `Verified ${new Date(source.verified_at).toLocaleString()}` : 'Verified'}</p><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap rounded bg-muted p-2 text-[10px]">{JSON.stringify(source.evidence, null, 2)}</pre></div>) : <p className="text-xs text-muted-foreground">No verified evidence sources for the current filter.</p>}</div></td></tr> : null}</React.Fragment>)}</tbody></table> : <div className="py-16 text-center text-sm text-muted-foreground">No requirement enrollments match these filters.</div>}</div>
  </section></div>
}

function leafNodes(nodes: any[]) { const parents = new Set(nodes.map((node) => node.parent_node_uuid).filter(Boolean)); return nodes.filter((node) => !parents.has(node.node_uuid)) }
function Loading() { return <div className="flex min-h-48 items-center justify-center"><Loader2 className="animate-spin text-muted-foreground" /></div> }
function Stat({ label, value }: any) { return <div className="rounded-lg bg-muted/60 p-4"><p className="text-2xl font-black">{value}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wide text-muted-foreground">{label}</p></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold"><span className="mb-2 block">{label}</span>{children}</label> }
